=== petya712/ID4JQM_XML_adatkez/ID4JQM_1005/sp_ertodtd.dtd
<?xml encoding="UTF-8"?>

        <!ELEMENT model (A*, B*, C*, A_B*)>
        <!ATTLIST model
  xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  xsi:noNamespaceSchemaLocation NMTOKEN #REQUIRED>
  
        <!ELEMENT A (Ab*, Ac)>
        <!ATTLIST A 
        	Aa CDATA #REQUIRED>
        <!ELEMENT Ab (Abx, Aby)>
        <!ELEMENT Abx (#PCDATA)>
        <!ELEMENT Aby (#PCDATA)>
        <!ELEMENT Ac (Acd, Ace)>
        <!ELEMENT Acd (#PCDATA)>
        <!ELEMENT Ace (#PCDATA)>
        <!ELEMENT B (Bb)>
        <!ATTLIST B
        	Ba CDATA #REQUIRED>
        <!ATTLIST A 
        	Bc CDATA #IMPLIED>
        <!ELEMENT Bb (Bbx, Bby)>
        <!ELEMENT Bbx (#PCDATA)>
        <!ELEMENT Bby (#PCDATA)>
        <!ELEMENT C (Cb)>
        <!ATTLIST C 
        	Ca CDATA #REQUIRED>
        <!ELEMENT Cb (#PCDATA)>
        <!ELEMENT A_B (A_Bc)>
        <!ELEMENT A_Bc (#PCDATA)>

=== petya712/ID4JQM_XML_adatkez/ID4JQM_1005/sp_xsdtoxml.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE model SYSTEM "sp_ertodtd.dtd">

<model
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="sp_ertoxsd.xsd">

    <A Aa="a">
        <Ab>
            <Abx>x</Abx>
            <Aby>y</Aby>
        </Ab>
        <Ac>
            <Acd>d</Acd>
            <Ace>e</Ace>
        </Ac>
    </A>

    <B Ba="a">
        <Bb>
            <Bbx>x</Bbx>
            <Bby>y</Bby>
        </Bb>
    </B>

    <C Ca="a">
        <Cb>b</Cb>
    </C>
    
    <A_B>
        <A_Bc>c</A_Bc>
    </A_B>

</model>
