=== petya712/ID4JQM_XML_adatkez/ID4JQM_1005/sp_konyv.dtd
<?xml encoding="UTF-8"?>

	<!ELEMENT konyvek (konyv)+>
	<!ATTLIST konyvek
  		xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
  		xsi:noNamespaceSchemaLocation NMTOKEN #REQUIRED>
        <!ELEMENT konyv (cim,pubEv,kiado,szerzo,abstract)>
        <!ATTLIST konyv
                id CDATA #REQUIRED>
        <!ELEMENT cim (#PCDATA)>
        <!ELEMENT pubEv (#PCDATA)>
        <!ELEMENT kiado (#PCDATA)>
        <!ELEMENT szerzo (#PCDATA)>
        <!ELEMENT abstract (#PCDATA)>

=== petya712/ID4JQM_XML_adatkez/ID4JQM_1005/sp_konyv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE konyvek SYSTEM "sp_konyv.dtd">

<konyvek>

    <konyv id="101">
        <cim>"XML_Alapok"</cim>
        <pubEv>"2005"</pubEv>
        <kiado>"Alexandra"</kiado>
        <szerzo>"Horvath_Janos"</szerzo>
        <abstract></abstract>
    </konyv>

    <konyv id="102">
        <cim>"Mobil_Programozasi_Alapok"</cim>
        <pubEv>"2002"</pubEv>
        <kiado>"Alexandra"</kiado>
        <szerzo>"Horvath_Bela"</szerzo>
        <abstract></abstract>
    </konyv>

    <konyv id="103">
        <cim>"Operacios_rendszerek_szerkezete"</cim>
        <pubEv>"1995"</pubEv>
        <kiado>"Mozaik"</kiado>
        <szerzo>"Vadasz_Denes"</szerzo>
        <abstract></abstract>
    </konyv>

</konyvek>
